close all;
clear all;
clc;

load 'coefs.mat'

N = size(h_rx_poly,2);
M = size(h_rx_poly,1);

%% Setup file for writing

fid = fopen('coefs.h','w');
fprintf(fid,'//-----------------------------------------------------------\n');
fprintf(fid,'// UCSD_MAS - V2X Motorcycle HUD\n');
fprintf(fid,'// Ryan Hiser, Jacob Nguyen, Jorge Pacheco\n');
fprintf(fid,'// file: coefs.h\n');
fprintf(fid,'// description: Coefficients for Poly Phase Filters\n');
fprintf(fid,'// Note: This file is generated by matlab create_coefs_h.m\n');
fprintf(fid,'//-----------------------------------------------------------\n');
fprintf(fid,'#ifndef COEFS_H_\n');
fprintf(fid,'#define COEFS_H_\n\n');

fprintf(fid,'#define NUMCOEFS %d\n',N);
fprintf(fid,'#define BANKS %d\n',M);

%% Matched Filter
fprintf(fid, 'const coef_t mf_rom[BANKS][NUMCOEFS] ={\n');
for m = 1:M
    fprintf(fid,"\t\t{");
    for n = 1:N
        if(n > 1)
            fprintf(fid,",%.20f",h_rx_poly(m,n));
        else
            fprintf(fid,"%.20f",h_rx_poly(m,n));
        end 
    end
    if(m == M)
        fprintf(fid,"}//%d\n",m);
    else
        fprintf(fid,"},//%d\n",m);
    end
end
fprintf(fid,'};\n\n');

%% Derivative Matched Filter
fprintf(fid, 'const coef_t dmf_rom[BANKS][NUMCOEFS] ={\n');
for m = 1:M
    fprintf(fid,"\t\t{");
    for n = 1:N
        if(n > 1)
            fprintf(fid,",%.20f",dh_rx_poly(m,n));
        else
            fprintf(fid,"%.20f",dh_rx_poly(m,n));
        end 
    end
    if(m == M)
        fprintf(fid,"}//%d\n",m);
    else
        fprintf(fid,"},//%d\n",m);
    end
end
fprintf(fid,'};\n\n');
%% End file writing
fprintf(fid,'\n#endif /*COEFS_H_*/\n');
fclose(fid);